### ISSUE TITLE
[MouseEvent] _sprite.graphics.lineTo/moveTo resulting to a DELAYED drawing

### ISSUE THREAD

**Issue by blackjyn** [matrix3d/spriteflexjs#28] opened 2020-01-24 12:23 UTC
I'm testing classic source for 'drawing' line with mouse on the stage, this is the code 
```
package
{
import flash.display.Sprite;
import flash.events.MouseEvent;

public class MouseEvt extends Sprite
{
	private var  _sprite:Sprite;
	
	public function MouseEvt()
	{		 
		_sprite=new Sprite();
		addChild(_sprite);
		_sprite.graphics.beginFill(0x556677);
		_sprite.graphics.drawRect(0,0,500,500);
		_sprite.graphics.endFill();
		
		_sprite.addEventListener(MouseEvent.MOUSE_DOWN,onMouseDown);
		_sprite.addEventListener(MouseEvent.MOUSE_UP,onMouseUp);
	}
	
	private function onMouseDown(e:MouseEvent):void
	{
		_sprite.graphics.lineStyle(3,0x551100,1);
		_sprite.graphics.moveTo(mouseX,mouseY);
		_sprite.addEventListener(MouseEvent.MOUSE_MOVE,onMouseMove);
	}
	
	private function onMouseUp(e:MouseEvent):void
	{
		_sprite.removeEventListener(MouseEvent.MOUSE_MOVE,onMouseMove);
	}
	
	private function onMouseMove(e:MouseEvent):void
	{
		_sprite.graphics.lineTo(mouseX,mouseY);
	} 
}
}
```

when compiled for SWF output via AIR SDK , resulting swf file handle the job sooo smoothly i.e. no delay when I click the mouse and start to moving it, it then draws the line.

While when compile to HTML+JS, the line will draws only after mouse's click is released.

![spriteflexjs-mouse-delayed](https://user-images.githubusercontent.com/6046191/73068860-d676e780-3ede-11ea-9b32-fb6be72b49c6.png)

System:
- Java 8 
- Royale 0.9.6

**Comment by matrix3d** [comment] 2020-02-12 02:01
可能是图形没有体积，没有接受鼠标移动事件

**Comment by blackjyn** [comment] 2020-02-12 04:38
I can't speak Chinese :crying_cat_face:

**Comment by matrix3d** [comment] 2020-02-12 04:50
Graphics doesn't seem to accept click events anymore. At first, there was. A commit code breaks that part of the code

**Comment by carlosrovira** [comment] 2020-02-12 11:14
Hi lizhi,
you mean with latest changes in develop (royale 0.9.7 current snapshot)?
Recently Greg Dove added support for flash graphics API, if that could be the cause I can highlight to Greg this issue so you both can see what could be the problem and solve it

**Comment by matrix3d** [comment] 2020-02-12 12:19
> Hi lizhi,
> you mean with latest changes in develop (royale 0.9.7 current snapshot)?
> Recently Greg Dove added support for flash graphics API, if that could be the cause I can highlight to Greg this issue so you both can see what could be the problem and solve it

I mean a problem with the code. Looks like graphics don't accept mouse movement events anymore
Does this example still show mouseMove?
https://github.com/matrix3d/spriteflexjs/blob/master/examples/src/TestMouseEvent.as
https://matrix3d.github.io/assets/html5/flexjsstage3d/bin/js-release/#test_mouse


Sorry, I do n’t have a development environment right now

**Comment by carlosrovira** [comment] 2020-02-12 14:20
Hi Lizhi,
sorry but I don't have this library compiled. I think others planned to bring maven build to it, and that's what I require to build and test. 
For now, I'll need to understand if some latest change caused some regression so I can help to notify and determine the problem. First I need to know If the problem is with latest changes in royale that we have in develop.

**Comment by blackjyn** [comment] 2020-02-12 14:23
Actually this sample below **works flawlessly**:
> https://matrix3d.github.io/assets/html5/flexjsstage3d/bin/js-release/#test_mouse

**Comment by carlosrovira** [comment] 2020-02-12 15:34
Hi @blackjyn, thanks for the example. Is this compiled with latest 0.9.7 in develop? And it worked recently? (so this means a regression)
thanks!

**Comment by blackjyn** [comment] 2020-02-12 20:36
No, I'm using v0.9.6

**Comment by kennylerma** [comment] 2020-02-12 21:05
I've planned to look at this.  I have other code to push as well, just busy as usual.

**Comment by carlosrovira** [comment] 2020-02-12 21:11
@blackjyn thanks, so it's not related to the change I was thinking of
@kennylerma thanks, hope you can do it finally. What about the plan to mavenize the build? can we expect that in the set of changes?

**Comment by kennylerma** [comment] 2020-02-12 21:21
@carlosrovira I don't think we'll be able to integrate into Royale anytime soon.  Royale as a framework is primarily focused on MXML/flex based projects and doesn't strictly adhere to reproducing the entire framework.  It may be possible in the future, but I think it's best to complete this library on it's own first.  Keeping it separate currently allows a lot more flexibility.  I saw Greg is working on graphics library as well which is likely more appropriate for mxml projects anyways.

**Comment by carlosrovira** [comment] 2020-02-12 21:38
Hi @kennylerma, I don't think is very needed to integrate into Royale, this could happen in the future as you say. I'm more interested in make it usable in maven an ease the use to add to Royale, the same as in Adobe days when Flex was able to load a Flash SWF file and show inside a Flex App. For that reason I'd like to have this project mavenized to integrate in a project easily. Then maybe (don't know) a Royale component to load SpriteFlexJS apps could be the missing link. Just some thoughts :)

**Comment by kennylerma** [comment] 2020-02-12 21:43
Ahh, I see.  That's a interesting idea.  I would need to learn more about Maven at some point to this, but I like the idea.  Just need to get more work done on the library first though.

**Comment by carlosrovira** [comment] 2020-02-12 21:53
Recently Royale Maven was improved. There's new work to simplify even more. If you want I can let you know as this forthcoming effort is committed to develop

**Closed** 2020-02-13 01:46 UTC

**Comment by matrix3d** [comment] 2020-02-13 04:17
Fewer and fewer people use flash and flash api. This library has only 81 stars and it is hard to get popular. So the update of this library is getting slower and slower.

**Comment by blackjyn** [comment] 2020-02-16 11:15
@carlosrovira 
> , the same as in Adobe days when Flex was able to load a Flash SWF file and show inside a Flex App.

> Then maybe (don't know) a Royale component to load SpriteFlexJS apps could be the missing link

I'm agree with this idea. 

@matrix3d despite its popularity, if this library is mature enough it HELPS A LOT of people out there who need to transpile their AS3 projects to HTML5.
These days I see a lot of poeple posting projects , asking for transpiling AS3 to HTML5 or even rewriting them., 
In case of transppiling very few tools are available, this library fills the gap
